services:
  - type: web
    name: vision-care-optical-api
    env: node
    region: singapore
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
